- title: weLearn
  description: Portfolio of web &amp; ui designer/developer hybrid Matthias Kretschmann.
  url: https://matthiaskretschmann.com
  email: m@kretschmann.io
  avatar: ../src/images/avatar.png
  img: ../src/images/twitter-card.png

  social:
    Email: mailto:contact@moodlearning.com
    Facebook: https://www.facebook.com/moodlearningph
    Twitter: https://twitter.com/moodlearning
    Instagram: https://www.instagram.com/moodlearning
    Linkedin: https://ph.linkedin.com/in/moodlearning
    Youtube: https://www.youtube.com/channel/UC3GHqqCI1wZNvnxF_16CobQ

  availability:
    status: false
    available: '👔 Available for new projects. <a href="mailto:m@kretschmann.io">Let’s talk</a>!'
    unavailable: Not available for new projects.

  # Footer actions
  gpg: https://kretschmann.io/pub.gpg
  addressbook: /matthias-kretschmann.vcf

  typekitID: dtg3zui

  # Analytics tools
  matomoUrl: https://analytics.kremalicious.com
  matomoSite: 2

  allowedHosts:
    - matthiaskretschmann.com
    - beta.matthiaskretschmann.com
    - localhost
