- title: weLearn
  description: Portfolio of lms &amp; moodLearning.
  url: https://www.moodlearning.com
  avatar: ../src/images/avatar.png
  img: ../src/images/twitter-card.png

  social:
    Facebook: https://www.facebook.com/moodlearningph
    Twitter: https://twitter.com/moodlearning
    Instagram: https://www.instagram.com/moodlearning
    Linkedin: https://ph.linkedin.com/in/moodlearning
    Youtube: https://www.youtube.com/channel/UC3GHqqCI1wZNvnxF_16CobQ

  availability:
    status: true
    available: '👔 Available for new projects. <a href="https://www.moodlearning.com/contact" target="_blank">Let’s talk</a>!'
    unavailable: Not available for new projects.

  # Footer actions
  typekitID: dtg3zui

  allowedHosts:
    - localhost
